export const GAME_CONFIG = {
  WIDTH: 480,
  HEIGHT: 720,

  SHIP_START_X: 240,
  SHIP_START_Y: 600,

  GRAVITY: 30,

  ROTATE_ACCELERATION: 300,
  ROTATE_ACCELERATION_MULTIPLIER: 1.0,
  ROTATE_MAX_SPEED: 360,
  MAX_TORQUE: 600,
  ROTATE_RAMP_UP_TIME: 0.25,
  ROTATE_RAMP_DOWN_TIME: 0.2,
  THRUST_RAMP_UP_TIME: 1.0,
  THRUST_RAMP_DOWN_TIME: 0.8,
  THRUST_FORCE: 40,
  RETRO_FORCE: 30,
  MAX_THRUST_FORCE: 0.5,

  FUEL_MAX: 100,
  FUEL_BURN_RATE: 10,

  FUEL_REFILL_BASE: 5,
  FUEL_REFILL_LANDED: 10,
  FUEL_REFILL_STOPPED: 60,

  BOUNCE_COEFFICIENT: 0.4,
  LAND_FRICTION: 0.1,

  ALTITUDE_GRAVITY_SCALE_HEIGHT: 2000,

  PLATFORM_WIDTH: 120,
  PLATFORM_HEIGHT: 16,
  PLATFORM_VERTICAL_SPACING: 300,
  PLATFORM_COUNT_VISIBLE: 6,

  OBSTACLE_SPAWN_CHANCE: 0.4,
  OBSTACLE_TYPES: ['triangle', 'rectangle', 'pentagon'] as const,

  COLOR_BG: 0x0a0a0f,
  COLOR_SHIP: 0x00e5ff,
  COLOR_THRUSTER_FLAME: 0xff6600,
  COLOR_PLATFORM: 0x44ff88,
  COLOR_PLATFORM_RECHARGING: 0x446644,
  COLOR_STAR: 0xffffff,
  COLOR_HUD: 0xffffff,
  COLOR_FUEL_BAR: 0x00e5ff,
  COLOR_FUEL_BAR_LOW: 0xff4444,
} as const;
